[package]
name = "vigenere"
version = "0.1.0"
authors = ["Jose A. Garcia <argantonio@gmail.com>"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[dependencies]
rustc-serialize = "0.3"
getopts = "0.2"
